// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2NeAP-8au8ej1qlPJ5ZY0-QfiFDLxIMM',
    appId: '1:472611515119:web:5f546ab32d2eba6781891a',
    messagingSenderId: '472611515119',
    projectId: 'billy-f2490',
    authDomain: 'billy-f2490.firebaseapp.com',
    storageBucket: 'billy-f2490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljdk5LSHyIKiBfJZVKXtt-D7AbQfzaHo',
    appId: '1:472611515119:android:9d59a0f072553eef81891a',
    messagingSenderId: '472611515119',
    projectId: 'billy-f2490',
    storageBucket: 'billy-f2490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBssqYz_rwYF6cKH6QRDdiVkBC_uwCfv0',
    appId: '1:472611515119:ios:22e80d38c8a3a3b081891a',
    messagingSenderId: '472611515119',
    projectId: 'billy-f2490',
    storageBucket: 'billy-f2490.appspot.com',
    iosClientId: '472611515119-mu775h9asbehkleonl2fnvboh4dc3ogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.billy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBssqYz_rwYF6cKH6QRDdiVkBC_uwCfv0',
    appId: '1:472611515119:ios:22e80d38c8a3a3b081891a',
    messagingSenderId: '472611515119',
    projectId: 'billy-f2490',
    storageBucket: 'billy-f2490.appspot.com',
    iosClientId: '472611515119-mu775h9asbehkleonl2fnvboh4dc3ogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.billy',
  );
}
